name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches: [ main ]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    services:
      postgres:
        env:
          POSTGRES_DB: carhist_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        image: postgres:13
        ports:
          - "5432:5432"
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/carhist_test"
      DATABASE_CACHE_URL: "postgres://postgres:postgres@localhost:5432/carhist_test"
      DATABASE_CABLE_URL: "postgres://postgres:postgres@localhost:5432/carhist_test"
      DATABASE_QUEUE_URL: "postgres://postgres:postgres@localhost:5432/carhist_test"
      CI: "y"
      SMTP_USERNAME: "x"

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bundle exec rubocop -f github
      - name: Lint ERB
        run: bundle exec erb_lint app/views/
      - name: Setup nodejs 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Yarn install
        uses: borales/actions-yarn@v5
        with:
          cmd: install # will run `yarn install` command
      - name: Lint Javascript files
        run: yarn run eslint app/javascript/
      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bundle exec brakeman --no-pager
      - name: Set up database schema
        run: bundle exec rails db:schema:load
      - name: Precompile assets
        run: yarn build && bundle exec rails assets:precompile
      - name: Run test models
        run: bundle exec rails test:models
      - name: Run test system
        run: bundle exec rails test:system
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: tmp/screenshots
