name: AI Scoring via Gemini CLI

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  score-and-analyze:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get PR Diff
        id: diff
        run: |
          curl -sL \
            -H "Accept: application/vnd.github.v3.diff" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
            > pr.diff

          {
            echo "diff<<EOF"
            cat pr.diff
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Run Gemini Review
        id: gemini
        uses: google-github-actions/run-gemini-cli@main
        env:
          CI: true
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            You are an AI code reviewer.
            Review the following pull request diff and give:
            - A score from 0–100 (only one number).
            - A list of weaknesses (do NOT provide solutions).
            - Ignore any `sleep` code under tests.
            - Analyze developer efficiency based on PR timing.

            PR submitted at: ${{ github.event.pull_request.created_at }}
            PR last updated at: ${{ github.event.pull_request.updated_at }}

            Pull Request #${{ github.event.pull_request.number }}
            Repository: ${{ github.repository }}

            --- BEGIN DIFF ---
            ${{ steps.diff.outputs.diff }}
            --- END DIFF ---

      - name: Post AI Review Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: gemini-score
          recreate: true
          message: |
            🤖 **Gemini AI Score & Analysis**
            ---
            ${{ steps.gemini.outputs.summary }}
