name: AI Scoring via Gemini CLI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  score-and-analyze:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get PR Diff
        id: diff
        run: |
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
            | jq -r '.diff_url' | xargs curl -s > pr.diff

          # Save diff content as multiline output
          {
            echo 'diff<<EOF'
            cat pr.diff
            echo 'EOF'
          } >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Gemini Review
        id: gemini
        uses: google-github-actions/run-gemini-cli@main
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            You are an AI code reviewer.
            Review the following pull request diff and give:
            - A score from 0–100 (only one number).
            - A list of weaknesses (do NOT provide solutions).
            - Ignore any `sleep` code under tests.

            Pull Request #${{ github.event.pull_request.number }}
            Repository: ${{ github.repository }}

            --- BEGIN DIFF ---
            ${{ steps.diff.outputs.diff }}
            --- END DIFF ---

      - name: Post AI Review Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: gemini-score
          message: |
            🤖 **Gemini AI Score & Analysis**
            ---
            ${{ steps.gemini.outputs.summary }}
